FROM python:3.10 AS build

COPY . /code
WORKDIR /code

RUN pip install -r requirements.txt && pip install pyinstaller

RUN pyinstaller --onefile shell.py

FROM scratch AS binaries

COPY --from=build /code/dist/shell /
